#!/usr/bin/env bash
# A file 0-custom_http_response_header so that it configures a brand new Ubuntu

apt-get -y update
apt-get -y install nginx

sed -i "52i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

service nginx start
