#!/usr/bin/env bash
# Installation and configuration of  HAproxy on your lb-01 server.

# Install HAproxy on a server
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
echo "

# configuration of the Haproxy
listen 3284-lb-01
        bind 0:80
        mode http
        stats enable
        balance roundrobin
        option httpclose
        option forwardfor
        server 182381-web-01 54.160.105.142
        server 182381-web-02 52.237.96.119
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
