#!/usr/bin/env bash
# A bash script that make my fix at task 1 short and sweet.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
