#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
my_store=1
while [ $my_store -le 20 ]
do
        echo "$my_store" 
	case $my_store in
		4) echo "bad luck from China"
		;;
		9) echo "bad luck from Japan"
		;;
		17) echo "bad luck from Italy"
		;;
	esac
        ((my_store++))
done
