#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server using the private
# key ~/.ssh/school with the user ubuntu.
# copy "SSH Public key" into ~/.ssh/authorized_keys
ssh -i ~/.ssh/school ubuntu@54.160.105.142
